name: Windows Build 

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Haxe and dependencies
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
      run: |
        choco install haxe --version 4.2.5 -y
        mkdir "%HAXELIB_ROOT%"
        haxelib setup "%HAXELIB_ROOT%"
        haxelib install lime openfl flixel flixel-tools flixel-ui hscript flixel-addons polymod actuate
        haxelib git faxe https://github.com/uhrobots/faxe
        haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons.git
        haxelib git polymod https://github.com/larsiusprime/polymod.git
        haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
        haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
        haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

    - name: Build Windows target
      run: haxelib run lime build windows

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows Build
        path: export/release/windows/bin/
